classtoday/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name="index"),
]

demoproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tasks/', include('tasks.urls')),
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('classtoday/', include("classtoday.urls")),
]

hello/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.index, name="index"),
    path("marc/", views.marc, name="marc"),
    path("uaa490/", views.uaa490, name="xyz"),
    path("<str:name>/", views.greet, name="greet"),

]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path('', views.index, name="index"),
    path('add-task/', views.add, name="add"),
]

classtoday/models.py
from django.db import models

# Create your models here.

hello/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

tasks/forms.py
from django import forms

class NewTaskForm(forms.form):
    task = forms.CharField(label="New Task", min_length=5)
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=3, initial=1)

    def clean(self):
        super(NewTaskForm, self.clean())

        t = self.cleaned_data('task')
        p = self.cleaned_data('priority')

        if p >= 4 and len(t) < 10:
            self._errors['task'] = self.error_class([
                'Minimum 10 chars needed when priority >= 4'
            ])
        return self.cleaned_data

classtoday/views.py
from django.shortcuts import render
import datetime

def index(request):
    now = datetime.datetime.now()
    classtoday = now.weekday()== 0 or now.weekday()==2
    return render(request, "classtoday/index.html", 
        {"currenttime": now,
         "classtoday": classtoday})

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, World!")

def marc0(request):
    return HttpResponse("Hello, Marc!")

def marc(request):
    return render(request, "hello/marc.html")

def uaa490(request):
    return HttpResponse("Hello, Class!")

def greet0(request, name):
    return HttpResponse(f'<h1>Greetings, {name.capitalize()}!!</h1><p>This space is available for a small fee</p>')

def greet(request, name):
    n = name.capitalize()
    return render(request, 'hello/greet.html', {"name": n})

tasks/views.py
from django.shortcuts import render, redirect
from .forms import NewTaskForm
from django.http import HttpResponseRedirect
from django.urls import reverse

tasks = ['eat', 'sleep', 'pray'
]

def index(request):
    return render(request, 'tasks/index.html', {
        'tasks': tasks
    })

def add(request):
    return render(request, "tasks/add.html")

def add(request):
    return render(request, "tasks/add.html", {"form": NewTaskForm()})

def add(request):
    if request.method == "POST":
        task = request.POST["task"]
        priority = request.POST["priority"]
        tasks.append(task)
        return render(request, 'tasks/index.html', {'tasks': tasks})
    return render(request, "tasks/add.html", {"form": NewTaskForm()})
    
def add(request):
    if request.method == "POST":
        task = request.POST["task"]
        priority = request.POST["priority"]
        tasks.append(task)
        #return HttpResponseRedirect(reverse('tasks:index'))
        return redirect('tasks:index') # similar functionality to previous line
    else:
        return render(request, "tasks/add.html", {"form": NewTaskForm()})
    
def add(request):
    if request.method == "POST":
        f = NewTaskForm(request.POST)
        if f.is_valid():
            task = request.POST["task"]
            priority = request.POST["priority"]
            tasks.append(task)
            return redirect('tasks:index')
        else:
            return render(request, 'tasks/add.html', {"from": f})

    else:
        return render(request, "tasks/add.html", {"form": NewTaskForm()})
    
def add(request):
    if request.method == "POST":
        f = NewTaskForm(request.POST)
        if f.is_valid():
            task = f.cleaned_data["task"]
            priority = f.cleaned_data["priority"]
            tasks.append(task)
            return redirect('tasks:index')
        else:
            return render(request, 'tasks/add.html', {"from": f})
    else:
        return render(request, "tasks/add.html", {"form": NewTaskForm()})

def add(request):
    if request.method == "POST":
        f = NewTaskForm(request.POST)
        if f.is_valid():
            task = f.cleaned_data["task"]
            priority = f.cleaned_data["priority"]
            if task not in tasks:
                tasks.append(task)
                return redirect('tasks:index')
            else: 
                return render (request, 'tasks/add.html', {
                    'form': f,
                    'errormessage': "Duplicate tasks aren't allowed"
                })
        else:
            return render(request, 'tasks/add.html', {"from": f})
    else:
        return render(request, "tasks/add.html", {"form": NewTaskForm()})

classtoday/templates/classtoday/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <link href="{% static 'classtoday/styles.css' %}" rel="stylesheet">
    <title>Any class?</title>
</head>
<body>
    <h1>Do we have class today? 
        {% if classtoday %}
         YES, we do!!!
        {% else %}
         Unfortunately, no class
        {% endif %}
    </h1>
    <p>It is currently {{ currenttime }}</p>
</body>
</html>

hello/templates/hello/greet.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <link href="https://cdn.simplecss.org/simple.css" rel="stylesheet">
    <title>hi</title>
</head>
<body>
    <h1>Howdie {{ name }}!</h1>

    <p style="color:red">This space is available</p>
</body>
</html>

hello/templates/hello/marc.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>hi marc</title>
</head>
<body>
    <h1>Howdie!</h1>
</body>
</html>

tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}

{% block contents %}
    <h1>New Task:</h1>
    {% if errormessage %}
        <p class="error">{{ errormessage }}</p>
    {% endif %}
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        <input type="text" name="t">
        <input type="submit">
    </form>

    <p><a href="{% url 'tasks:index'%}">List tasks</a></p>
{% endblock %}

tasks/templates/tasks/index.html
 {% extends 'tasks/layout.html' %}

 {% block contents %}
    <h1>My Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul> 

    <p><a href="{% url 'tasks:add'%}">Add a task</a></p>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>Tasks</title>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    <style>
        .error {
            color: red;
        }
    </style>
</head>
<body>

    {% block contents %}
    {% endblock %}
    <footer>
        <p>Copyright UAA490 2023</p>
    </footer>
</body>
</html>